version: '3'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "0.0.0.0:27017:27017/tcp"
    command: --logpath /dev/null

volumes:
  backend:
  frontend:
  mongodb:

